/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.tasks.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>tasks</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.sonicle.webtop.tasks.jooq.tables.records.CategoriesRecord, java.lang.Integer> IDENTITY_CATEGORIES = Identities0.IDENTITY_CATEGORIES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoriesRecord> CATEGORIES_PKEY = UniqueKeys0.CATEGORIES_PKEY;
	public static final org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropsRecord> CATEGORY_PROPS_PKEY = UniqueKeys0.CATEGORY_PROPS_PKEY;
	public static final org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.TasksRecord> TASKS_PKEY = UniqueKeys0.TASKS_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.sonicle.webtop.tasks.jooq.tables.records.CategoriesRecord, java.lang.Integer> IDENTITY_CATEGORIES = createIdentity(com.sonicle.webtop.tasks.jooq.tables.Categories.CATEGORIES, com.sonicle.webtop.tasks.jooq.tables.Categories.CATEGORIES.CATEGORY_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoriesRecord> CATEGORIES_PKEY = createUniqueKey(com.sonicle.webtop.tasks.jooq.tables.Categories.CATEGORIES, com.sonicle.webtop.tasks.jooq.tables.Categories.CATEGORIES.CATEGORY_ID);
		public static final org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropsRecord> CATEGORY_PROPS_PKEY = createUniqueKey(com.sonicle.webtop.tasks.jooq.tables.CategoryProps.CATEGORY_PROPS, com.sonicle.webtop.tasks.jooq.tables.CategoryProps.CATEGORY_PROPS.DOMAIN_ID, com.sonicle.webtop.tasks.jooq.tables.CategoryProps.CATEGORY_PROPS.USER_ID, com.sonicle.webtop.tasks.jooq.tables.CategoryProps.CATEGORY_PROPS.CATEGORY_ID);
		public static final org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.TasksRecord> TASKS_PKEY = createUniqueKey(com.sonicle.webtop.tasks.jooq.tables.Tasks.TASKS, com.sonicle.webtop.tasks.jooq.tables.Tasks.TASKS.TASK_ID);
	}
}
