/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.tasks.jooq;

/**
 * Convenience access to all tables in tasks
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table tasks.categories
	 */
	public static final com.sonicle.webtop.tasks.jooq.tables.Categories CATEGORIES = com.sonicle.webtop.tasks.jooq.tables.Categories.CATEGORIES;

	/**
	 * The table tasks.category_property_sets
	 */
	public static final com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets CATEGORY_PROPERTY_SETS = com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS;

	/**
	 * The table tasks.tasks
	 */
	public static final com.sonicle.webtop.tasks.jooq.tables.Tasks TASKS = com.sonicle.webtop.tasks.jooq.tables.Tasks.TASKS;
}
