/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.tasks.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryPropertySets extends org.jooq.impl.TableImpl<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord> {

	private static final long serialVersionUID = 1938774266;

	/**
	 * The reference instance of <code>tasks.category_property_sets</code>
	 */
	public static final com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets CATEGORY_PROPERTY_SETS = new com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord> getRecordType() {
		return com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord.class;
	}

	/**
	 * The column <code>tasks.category_property_sets.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>tasks.category_property_sets.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>tasks.category_property_sets.category_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord, java.lang.Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tasks.category_property_sets.hidden</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord, java.lang.Boolean> HIDDEN = createField("hidden", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>tasks.category_property_sets.color</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord, java.lang.String> COLOR = createField("color", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>tasks.category_property_sets.sync</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord, java.lang.String> SYNC = createField("sync", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * Create a <code>tasks.category_property_sets</code> table reference
	 */
	public CategoryPropertySets() {
		this("category_property_sets", null);
	}

	/**
	 * Create an aliased <code>tasks.category_property_sets</code> table reference
	 */
	public CategoryPropertySets(java.lang.String alias) {
		this(alias, com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS);
	}

	private CategoryPropertySets(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord> aliased) {
		this(alias, aliased, null);
	}

	private CategoryPropertySets(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.tasks.jooq.Tasks.TASKS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord> getPrimaryKey() {
		return com.sonicle.webtop.tasks.jooq.Keys.CATEGORY_PROPERTY_SETS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord>>asList(com.sonicle.webtop.tasks.jooq.Keys.CATEGORY_PROPERTY_SETS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets as(java.lang.String alias) {
		return new com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets rename(java.lang.String name) {
		return new com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets(name, null);
	}
}
