/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.tasks.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryPropertySetsRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.tasks.jooq.tables.records.CategoryPropertySetsRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1021096259;

	/**
	 * Setter for <code>tasks.category_property_sets.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tasks.category_property_sets.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>tasks.category_property_sets.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tasks.category_property_sets.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>tasks.category_property_sets.category_id</code>.
	 */
	public void setCategoryId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tasks.category_property_sets.category_id</code>.
	 */
	public java.lang.Integer getCategoryId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>tasks.category_property_sets.hidden</code>.
	 */
	public void setHidden(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tasks.category_property_sets.hidden</code>.
	 */
	public java.lang.Boolean getHidden() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>tasks.category_property_sets.color</code>.
	 */
	public void setColor(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tasks.category_property_sets.color</code>.
	 */
	public java.lang.String getColor() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>tasks.category_property_sets.sync</code>.
	 */
	public void setSync(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tasks.category_property_sets.sync</code>.
	 */
	public java.lang.String getSync() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.String, java.lang.String, java.lang.Integer> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.Integer, java.lang.Boolean, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS.CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS.HIDDEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS.COLOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS.SYNC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getHidden();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getColor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSync();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord value1(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord value3(java.lang.Integer value) {
		setCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord value4(java.lang.Boolean value) {
		setHidden(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord value5(java.lang.String value) {
		setColor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord value6(java.lang.String value) {
		setSync(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CategoryPropertySetsRecord values(java.lang.String value1, java.lang.String value2, java.lang.Integer value3, java.lang.Boolean value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CategoryPropertySetsRecord
	 */
	public CategoryPropertySetsRecord() {
		super(com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS);
	}

	/**
	 * Create a detached, initialised CategoryPropertySetsRecord
	 */
	public CategoryPropertySetsRecord(java.lang.String domainId, java.lang.String userId, java.lang.Integer categoryId, java.lang.Boolean hidden, java.lang.String color, java.lang.String sync) {
		super(com.sonicle.webtop.tasks.jooq.tables.CategoryPropertySets.CATEGORY_PROPERTY_SETS);

		setValue(0, domainId);
		setValue(1, userId);
		setValue(2, categoryId);
		setValue(3, hidden);
		setValue(4, color);
		setValue(5, sync);
	}
}
